### ISSUE TITLE
[BUG]社交links会错误地被显示

### ISSUE THREAD

**Issue by Lemonawa** [Siricee/hexo-theme-Chic#119]
配置：
```
links:
  Blog: /archives
  # Category:
  # Tags: 
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # ZhiHu: https://www.zhihu.com/people/sirice
  # LinkedIn:
  # FaceBook:
  Twitter: https://twitter.com/@realLemonawa
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  # Weibo:
  # WeChat:
  Github: https://github.com/Lemonawa
```
显示效果：
![image](https://user-images.githubusercontent.com/69106050/157909800-63c9b54f-62f0-45c6-b2ac-3a86cb243100.png)
