### ISSUE TITLE
Theme doesn't fully load

### ISSUE THREAD

**Issue by Ziadey** [Siricee/hexo-theme-Chic#12]
I have installed the theme to [domain]/themes/Chic, and I have modified the theme setting in [domain]/_config.yml to Chic.
![image](https://user-images.githubusercontent.com/31080766/62838624-4e2dbe80-bc7f-11e9-90f3-3508cee1ea46.png)

The issue here is that the theme doesn't fully load. There is no code inside the webpage. Only the favicon of Hexo (from [domain]/themes/Chic/source/favicon.ico) has loaded.
![image](https://user-images.githubusercontent.com/31080766/62838615-36eed100-bc7f-11e9-9cc0-a160cf0cb31c.png)

Note that in [domain]/_config.yml, the URL setting is fine, and it works for other themes.
![image](https://user-images.githubusercontent.com/31080766/62838673-de6c0380-bc7f-11e9-9e68-02266939bbef.png)

I use Gitlab for my blog.
Did I do anything wrong?

**Comment by Siricee** [comment]
Did you run the command `hexo server` to test your site in your localhost? If preview on your localhost works, that means config file is correct.

I think the parts you mentioned are correct. So I doubt that whether your **deploy** config is something wrong. you may need to check your deploy configuration.

Here is my preview site configuration below for your reference.([domain]/_config.yml )
```yaml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Siricee/hexo-theme-Chic.git
  branch: gh-pages
```
I have not tested on gitlab ever before , But I think github and gitlab are similar.

Hope this is helpful for you, Best.
