### ISSUE TITLE
主题首页链接“Tag”页面的图标开启

### ISSUE THREAD

**Issue by greedy-hat** [Siricee/hexo-theme-Chic#13]
就是博客标签页图标显示不了

**Comment by Siricee** [comment]
你说的是首页的图标吗，（如图）
![QQ图片20190812194003](https://user-images.githubusercontent.com/25154957/62862691-2f8bfe00-bd39-11e9-9282-43d70f7bd69c.png)
这里需要在主题配置文件中做如下配置：
```yaml
# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /
#  Category:
  Tags: tag # 这里取消注释并添加值tag
#  Link:
#  Resume:
```

希望可以帮到你，祝你使用愉快。
