### ISSUE TITLE
评论暗色模式适配

### ISSUE THREAD

**Issue by JesseJeson** [Siricee/hexo-theme-Chic#130]
[链接](https://waline.js.org/guide/client/style.html#%E6%9A%97%E9%BB%91%E6%A8%A1%E5%BC%8F%E6%94%AF%E6%8C%81)

文中提到网站的两种暗色模式方式，请问本主题使用的是哪一种，如果是第二种，那么具体方法是什么
（前端小白，请谅解QWQ）
谢谢！

**Comment by Siricee** [comment]
我用的第二种，动态添加class的。暗黑模式下body会多一个'dark-theme'的class。
根据这个文档，你要写的css选择器应该是
```css
body.dark-theme{
/* 常规颜色 */
  --waline-white: #000;
  --waline-light-grey: #666;
  --waline-dark-grey: #999;

  /* 布局颜色 */
  --waline-color: #888;
  --waline-bgcolor: #1e1e1e;
  --waline-bgcolor-light: #272727;
  --waline-border-color: #333;
  --waline-disable-bgcolor: #444;
  --waline-disable-color: #272727;

  /* 特殊颜色 */
  --waline-bq-color: #272727;

  /* 其他颜色 */
  --waline-info-bgcolor: #272727;
  --waline-info-color: #666;
}
```
