### ISSUE TITLE
请求在 Chic 主题中添加文章内目录功能

### ISSUE THREAD

**Issue by greendolphindance** [Siricee/hexo-theme-Chic#138]
您好！首先感谢您开发了 Chic 主题，我非常喜欢。

我有一个请求，希望能在 Chic 主题中添加文章内目录的功能。我尝试了一些在线教程来实现这个功能，但效果都不是很理想。唯一成功的尝试是通过这个教程（[链接](https://cloud.tencent.com/developer/article/2065866)），但生成的目录有一些问题：

- 目录固定在文章顶部，这样在阅读文章时不太方便。
- 点击目录中的内容无法正确跳转到相应的部分。
- 生成的目录视觉效果不太美观。

您可以在这里查看我实现的效果：[示例](https://greendolphindance.com/2023/10/07/博客搭建小记)

如果可能的话，我希望您能考虑开发这个功能。比如，在屏幕右下角显示一个可以展开目录的图标，这样在阅读文章时会更加方便。

另外，如果您现在没有兴趣或精力开发这个功能，也麻烦您或许能不能帮我看一下，为什么我实现的目录点击后无法跳转。

非常感谢您的帮助和付出！期待您的回复。

**Comment by greendolphindance** [comment]
啊啊啊，点击后无法跳转的问题解决了，原来是_config.yml里没有配置好。修改后的版本：

```
toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: before
    symbol: ''
    style: header-anchor
```

但还是暗戳戳期待一个更美丽的目录功能！鞠躬！
