### ISSUE TITLE
新手，问一下如何转中文

### ISSUE THREAD

**Issue by Geeklinus** [Siricee/hexo-theme-Chic#149]

**Comment by Siricee** [comment]
直接在yaml文件里写中文就行，开发时没做自动多语言设置

举个例子, _config.yaml文件里
```yaml
# Header
navname: Bentham's Blog

# navigatior items
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about
```
改成
```yaml
# Header
navname: 我的博客

# navigatior items
nav:
  文章: /archives
  分类: /category
  标签: /tag
  关于: /about
```

后面的是目录，这个不要改，改了就找不到文件了。至于其他部分，可以看看别人的issues里面有些会提到，有的用户已经设置了中文你直接抄一下他的config就行了
