### ISSUE TITLE
请问作者，如何优化搜索引擎的显示内容？

### ISSUE THREAD

**Issue by LianZhuotao** [Siricee/hexo-theme-Chic#28]
![image](https://user-images.githubusercontent.com/50575245/67069881-7d9a0380-f1b9-11e9-9924-622b3d23a28b.png)
1.如图，我想让他显示成 某某的博客 之类的，应该在何处修改？（或者在何处修改能避免他自动生成对网站的描述）
2.主页的<title>，还有meta name这种在何处设置？
谢谢您的回答。

**Comment by Siricee** [comment]
1. SEO部分在博客全局配置([root]/_config.yml)中修改
```yaml
# Site
title:
subtitle:
description: 
keywords: 
author: 
language: 
timezone:
```
2. 你说的`title`还有`meta`相关标签可以在`hexo-theme-Chic/layout/_partial/head.ejs`中修改，其中`title`字段是根据不同页面生成的，你可以以自己的方式实现，重写那个标签中的函数就行。

另外（虽然我自己没用过）hexo是有SEO插件可以用的，你可以搜一下
