### ISSUE TITLE
博客部署后静态资源丢失

### ISSUE THREAD

**Issue by mengyu666** [Siricee/hexo-theme-Chic#52]

**Comment by mengyu666** [comment]
尊敬的作者：
您好！ 新年快乐！
我有一些问题，想向您请教一下：
当我在在加载后，页面出现了以下页面，不管是pc还是手机打开网页都是这样，但当我在本地用4000端口浏览时，是正常显示页面，缩放正常。
![屏幕截图(130)](https://user-images.githubusercontent.com/58378454/73117388-df6bc580-3f7f-11ea-9671-3ab6b408eace.png)
请问一下我该做些什么，谢谢！

**Comment by mengyu666** [comment]
您好，这是我用4000端口打开的正常显示：
![屏幕截图(132)](https://user-images.githubusercontent.com/58378454/73117485-5a81ab80-3f81-11ea-996f-51ae37af2ba7.png)

**Comment by Siricee** [comment]
从你的图片上可以看出，应该是你的部署路径错了，你可能是把root填成`mengyu666.github.io`或者把url填成了`www.raomengyu.top/mengyu666.github.io` ，所以找不到css资源了。

**关于路径部署在我的[文档-FAQ](https://github.com/Siricee/hexo-theme-Chic#faq)里特意提到过这个问题**。

我猜你应该是想在`www.raomengyu.top/`路径下部署，那你的博客根目录config.yml应该这样写：(注意url和root)
```yml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: www.raomengyu.top # this is your deploy url.
root: /  # this is your root folder url.
permalink: :year/:month/:day/:title/
permalink_defaults:
```
本地开发模式（hexo s）下这个字段不会被调用，只有部署时才会用得到。

如果有帮到你，请点个star支持一下谢谢，祝新年快乐
