### ISSUE TITLE
怎样将点击图片的超链接链接到我的博客啊

### ISSUE THREAD

**Issue by meike01** [Siricee/hexo-theme-Chic#65]
现在我的主页中心的图片只能跳转到网页根目录，无法点击到达博客页面。

还有就是语言其实不起作用，我已经将主页的配置文件的语言设置成了中文，但是不起任何作用。

**Comment by Siricee** [comment]
> 现在我的主页中心的图片只能跳转到网页根目录，无法点击到达博客页面。

这可能是你的网站地址设置的不正确，具体设置请参考FAQ中第一个问题。

如果想跳转到其他链接你可以修改[这里](https://github.com/Siricee/hexo-theme-Chic/blob/f4de2af7a5f18a82c814063f3727eaa8b8c99c58/layout/_page/profile.ejs#L4)

> 还有就是语言其实不起作用，我已经将主页的配置文件的语言设置成了中文，但是不起任何作用。

语言字段不能使用，我的主题没有做国际化处理。你可以直接在config.yaml中用中文。
举个例子
```yaml
nav:
  Posts: /archives
  Categories: /category
  Tags: /tag
  About: /about
改为
nav:
  文章: /archives
  分类: /category
  标签: /tag
  关于: /about
```
注意冒号是英文冒号
