### ISSUE TITLE
如何将列表的日期 10号以内的日期 前加上0

### ISSUE THREAD

**Issue by kakarrot0109** [Siricee/hexo-theme-Chic#88]
categories archives tags页面的列表日期 

文章md源文件的日期是`date: 2019-10-14 00:00:00`

修改前`八月 6, 2020`
修改后`八月 06, 2020`

**Comment by Siricee** [comment]
请到主题配置文件中 `hexo-theme-Chic/_config.yml` Date部分
```yaml
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMMM D, YYYY => MMMM DD, YYYY
time_format: H:mm:ss
```
将 date_format字段从 MMMM D, YYYY 改为 MMMM DD, YYYY 即可。
